---
users:
  - username: admin
    email: email@example.com
    name: Admin User
    type: admin
    credentials:
      # password: foobar_123
      password: $2a$14$ARw0H6VNqMQ5Whp8HaoefuWE.xjCdQ1rfVszILwJ3hgXRqF7L3ZVe
      tokens:
        - name: Admin api token  
          value: some_testing_admin_api_token_11345678
          scopes:
            - full

  - username: system
    email: system@localhost
    name: System user
    type: system

  - username: testuser1
    email: testuser1@example.com
    name: Test User1
    type: user
    credentials:
      # password: foobar_123
      password: $2a$14$ARw0H6VNqMQ5Whp8HaoefuWE.xjCdQ1rfVszILwJ3hgXRqF7L3ZVe
    

## Clients
clients:
  - client_id: system 
    name: System client
    description: System client for internal use only
    type: internal
  
  - client_id: test_oauth2
    name: Testing oauth2 client
    description: Testing OAuth 2.0 client
    type: confidential
    auth_config:
      scopes:
        - test_scope:r
        - test_scope2:w
      oauth2_flows:
        client_credentials:
          enabled: true
        authorization_code_grant:
          enabled: true
        resource_owner:
          enabled: true
      client_secret: test_oauth2_client_secret
      redirect_uris:
        - https://127.0.0.1:8080/oauth2/callback
      tokens:
        access:
          expires_in: 360s
        refresh:
          single_use: true
          expires_in: 720h


